### ISSUE TITLE
Does Askless support the SSL/TLS protocol? If so, how can I implement it on my Node.js server?

### ISSUE THREAD

**Issue by hung1998hy** [RodrigoBertotti/Askless#5]
Hi Rodrigo,

I am currently developing a real-time chat application using Flutter and Node.js. I am unsure if the packets transmitted between the client and server are encrypted. If the packets are not encrypted, how should I implement the encryption?

Thanks.

**Comment by RodrigoBertotti** [comment]
Hello!

Askless works with the WebSocket protocol

You should configure SSL on Nginx so you can connect with `wss://<your URL>`

**Comment by RodrigoBertotti** [comment]
Hello! Yes, Askless supports SSL/TLS because it works with the WebSocket protocol, is not encrypted by default

You should configure SSL on Nginx so you can connect with `wss://<your URL>` 

To do that, you should set your SSL configuration (starting with `ssl_`) on Nginx as you would configure for any other server and that should work fine :)

**Comment by hung1998hy** [comment]
Hello,

I am using your flutter_chat_app_with_nodejs project to learn Flutter and Node.js. I want to use `wss://<your URL>` instead of `wss://<your URL>`. As I understand, besides configuring SSL, I will need to adjust the index.ts file to use `wss://<your URL>`.
